### ISSUE TITLE
Image Description

### ISSUE THREAD

**Issue by CarlRosschou** [nlbdev/nordic-epub3-dtbook-migrator#244] opened 2014-12-10 10:24 UTC
Does anyone have considerations regarding image description? It might be a good idea to have a uniform way to handle it. 
Since W3C has issued a Proposed Recommendation for longdesc attribute to link descriptions to images, Nota will probably go for this solution sometime in the future.

**Comment by josteinaj** [comment] 2015-02-11 13:56
I consider this a duplicate of #218 so I'm closing it.

**Closed** 2015-02-11 13:56 UTC
Labels: 5 - Done, enhancement, guidelines revision
