### ISSUE TITLE
Improve dependency management

### ISSUE THREAD

**Issue by joeha480** [nlbdev/nordic-epub3-dtbook-migrator#326] opened 2015-05-26 08:22 UTC
As far as I know, snapshot versions of dependencies are used in the released version of the Nordic migrator. This makes for an unreliable deploy since we try to get all dependencies from maven central (and not from the dependencies zip). If these snapshots are updated in the period between release and packaging there is no quality control of the release. Would it be possible to rely only on released versions?

Currently, in our rpm packaging of the nordic migrator (see https://github.com/mtmse/nordic-epub3-dtbook-assembly) we have a manual list collected from the dependencies zip that we then use to fetch the artifacts from maven central (and snapshot repo). However if the dependencies change, this breaks. It would be great if these dependencies were included in the nordic migrator pom, so that we can update the dependencies automatically.

**Comment by josteinaj** [comment] 2015-05-26 09:12
I agree and would like to do this as soon as it becomes possible.

The problem is that the nordic migrator depends on an unreleased version of epubcheck for validation. The latest *released* version of epubcheck is incompatible with Pipeline 2, but if you build the master branch of epubcheck it should work (see IDPF/epubcheck#471, IDPF/epubcheck#375, IDPF/epubcheck#417 and IDPF/epubcheck#415). As soon as a new version of epubcheck is released, we can depend on that version. Hopefully epubcheck will also be included as a script in a future version of Pipeline 2, in which case there will be no additional dependencies for the nordic migrator. All the current dependencies are due to the unreleased version of epubcheck.

Blocked on: daisy/pipeline-scripts-utils#56

See also: #307 and #119

**Comment by josteinaj** [comment] 2018-05-03 08:56
Fixed in [v1.2.0](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/commit/5c4e01fe0161b8d205b7bf96be359ff5817f7cf2)

**Closed by josteinaj** 2018-05-03 08:56 UTC
Labels: 1 - Medium priority, enhancement
