### ISSUE TITLE
Nordic EPUB3 to DTBook sets wrong XML-encoding in output

### ISSUE THREAD

**Issue by olavindergaard** [nlbdev/nordic-epub3-dtbook-migrator#355] opened 2018-04-13 07:45 UTC
`<?xml version="1.0" encoding="utf-8"?>` in input results in `<?xml version="1.0" encoding="us-ascii"?>` in output

**Comment by josteinaj** [comment] 2018-04-25 13:26
Duplicate of #318

**Closed by josteinaj** 2018-04-25 13:26 UTC
